controller_list:
  - name: fake_gantry_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_e1
      - joint_e2
      - joint_e3
initial:  # Define initial robot poses per group
  - group: gantry
    pose: test