position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_e1
    - joint_e2
    - joint_e3
  gains:
    joint_e1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_e2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_e3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1