#Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 250

# Joint trajectory controller
manipulator_position_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6
  joint_limits:
    joint_a1:
      has_velocity_limits: true
      max_velocity: 0.000001
      has_acceleration_limits: true
      max_acceleration: 0.0000001
    joint_a2:
      has_velocity_limits: true
      max_velocity: 2.0
      has_acceleration_limits: true
      max_acceleration: 5.0
      has_jerk_limits: true
      max_jerk: 100.0
    joint_a3:
      has_velocity_limits: true
      max_velocity: 2.0
      has_acceleration_limits: true
      max_acceleration: 5.0
      has_jerk_limits: true
      max_jerk: 100.0
    joint_a4:
      has_velocity_limits: true
      max_velocity: 2.0
      has_acceleration_limits: true
      max_acceleration: 5.0
      has_jerk_limits: true
      max_jerk: 100.0
    joint_a5:
      has_velocity_limits: true
      max_velocity: 2.0
      has_acceleration_limits: true
      max_acceleration: 5.0
      has_jerk_limits: true
      max_jerk: 100.0
    joint_a6:
      has_velocity_limits: true
      max_velocity: 2.0
      has_acceleration_limits: true
      max_acceleration: 5.0
      has_jerk_limits: true
      max_jerk: 100.0
  state_publish_rate: 250 # Defaults to 50
  action_monitor_rate: 20 # Defaults to 20

# Joint trajectory controller
gantry_position_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - joint_e1
    - joint_e2
    - joint_e3
  joint_limits:
    joint_e1:
      has_velocity_limits: true
      max_velocity: 2.0
      has_acceleration_limits: true
      max_acceleration: 1.0
      has_jerk_limits: true
      max_jerk: 100.0
    joint_e2:
      has_velocity_limits: true
      max_velocity: 2.0
      has_acceleration_limits: true
      max_acceleration: 2.0
      has_jerk_limits: true
      max_jerk: 100.0
    joint_e3:
      has_velocity_limits: true
      max_velocity: 2.0
      has_acceleration_limits: true
      max_acceleration: 1.0
      has_jerk_limits: true
      max_jerk: 100.0
  state_publish_rate: 250 # Defaults to 50
  action_monitor_rate: 20 # Defaults to 20
