#Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 250

# Joint trajectory controller
position_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - master_joint_a1
    - master_joint_a2
    - master_joint_a3
    - master_joint_a4
    - master_joint_a5
    - master_joint_a6
    - master_joint_e1
    - master_joint_e2
  state_publish_rate: 250 # Defaults to 50
  action_monitor_rate: 20 # Defaults to 20
  

