controller_joint_names: ["slave_joint_a1", "slave_joint_a2", "slave_joint_a3", "slave_joint_a4", "slave_joint_a5", "slave_joint_a6", "slave_joint_e1", "slave_joint_e2", "slave_joint_e3"]

ndof: 9

#Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 250

# Joint trajectory controller
position_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - slave_joint_a1
    - slave_joint_a2
    - slave_joint_a3
    - slave_joint_a4
    - slave_joint_a5
    - slave_joint_a6
    - slave_joint_e1
    - slave_joint_e2
    - slave_joint_e3

  state_publish_rate: 250 # Defaults to 50
  action_monitor_rate: 20 # Defaults to 20
